"""
Parallel quiz items used by POST /repair-check.

Each entry targets the same concept as an existing seed question, at the
same difficulty, so a repair probe and a parallel post-repair check exist
for the concepts used in the demo chain.
"""
from __future__ import annotations

from .models import Difficulty, Question, QuestionOption


def _opts(*pairs: tuple[str, str]) -> list[QuestionOption]:
    return [QuestionOption(id=i, text=t) for i, t in pairs]


PARALLEL_QUESTIONS: list[Question] = [
    Question(id="q.num.operations.02",
             prompt="Evaluate: 10 - 2 x 3",
             options=_opts(("a", "24"), ("b", "4"), ("c", "16"), ("d", "8")),
             correct_option_id="b",
             answer_rubric="Multiplication first: 2 x 3 = 6, then 10 - 6 = 4.",
             target_concept_id="num.operations",
             prerequisite_tags=["num.integers"],
             difficulty=Difficulty.EASY, reviewed=True),
    Question(id="q.num.signed.02",
             prompt="Compute: -8 + 5",
             options=_opts(("a", "-13"), ("b", "-3"), ("c", "3"), ("d", "13")),
             correct_option_id="b",
             answer_rubric="Start at -8, move 5 right: -3.",
             target_concept_id="num.signed",
             prerequisite_tags=["num.integers"],
             difficulty=Difficulty.EASY, reviewed=True),
    Question(id="q.alg.variables.02",
             prompt="If y = 3, what is the value of 4y - 1?",
             options=_opts(("a", "11"), ("b", "12"), ("c", "13"), ("d", "8")),
             correct_option_id="a",
             answer_rubric="4(3) - 1 = 12 - 1 = 11.",
             target_concept_id="alg.variables",
             prerequisite_tags=["num.operations"],
             difficulty=Difficulty.EASY, reviewed=True),
    Question(id="q.alg.combine_like.02",
             prompt="Simplify: 7a - 2b + 3a + b",
             options=_opts(("a", "10a - b"), ("b", "10a - 3b"),
                           ("c", "4a - b"), ("d", "9ab")),
             correct_option_id="a",
             answer_rubric="a-terms: 7a + 3a = 10a. b-terms: -2b + b = -b.",
             target_concept_id="alg.combine_like",
             prerequisite_tags=["alg.variables"],
             difficulty=Difficulty.MEDIUM, reviewed=True),
    Question(id="q.alg.distribute.02",
             prompt="Expand: 5(x + 2)",
             options=_opts(("a", "5x + 2"), ("b", "5x + 10"),
                           ("c", "x + 10"), ("d", "5x + 7")),
             correct_option_id="b",
             answer_rubric="5*x + 5*2 = 5x + 10.",
             target_concept_id="alg.distribute",
             prerequisite_tags=["alg.combine_like"],
             difficulty=Difficulty.EASY, reviewed=True),
    Question(id="q.alg.one_step.02",
             prompt="Solve for x: x - 4 = 9",
             options=_opts(("a", "x = 5"), ("b", "x = 13"),
                           ("c", "x = -5"), ("d", "x = 36")),
             correct_option_id="b",
             answer_rubric="Add 4 to both sides: x = 13.",
             target_concept_id="alg.one_step",
             prerequisite_tags=["alg.combine_like"],
             difficulty=Difficulty.EASY, reviewed=True),
    Question(id="q.alg.two_step.02",
             prompt="Solve for x: 3x - 5 = 10",
             options=_opts(("a", "x = 5"), ("b", "x = 15"),
                           ("c", "x = 5/3"), ("d", "x = 45")),
             correct_option_id="a",
             answer_rubric="Add 5: 3x = 15. Divide by 3: x = 5.",
             target_concept_id="alg.two_step",
             prerequisite_tags=["alg.one_step"],
             difficulty=Difficulty.MEDIUM, reviewed=True),
    Question(id="q.alg.poly_mul.02",
             prompt="Expand: (x + 1)(x + 4)",
             options=_opts(("a", "x^2 + 5x + 4"), ("b", "x^2 + 4x + 4"),
                           ("c", "x^2 + 5x + 5"), ("d", "x^2 + 4")),
             correct_option_id="a",
             answer_rubric="FOIL: x^2 + 4x + x + 4 = x^2 + 5x + 4.",
             target_concept_id="alg.poly_mul",
             prerequisite_tags=["alg.distribute"],
             difficulty=Difficulty.MEDIUM, reviewed=True),
    Question(id="q.alg.factoring.02",
             prompt="Factor: x^2 + 7x + 12",
             options=_opts(("a", "(x + 3)(x + 4)"), ("b", "(x + 2)(x + 6)"),
                           ("c", "(x - 3)(x - 4)"), ("d", "(x + 1)(x + 12)")),
             correct_option_id="a",
             answer_rubric="Need factors of 12 summing to 7: 3 and 4.",
             target_concept_id="alg.factoring",
             prerequisite_tags=["alg.poly_mul", "alg.gcf"],
             difficulty=Difficulty.HARD, reviewed=True),
    Question(id="q.alg.quadratic_eq.02",
             prompt="Solve by factoring: x^2 - 9 = 0",
             options=_opts(("a", "x = 3 or x = -3"), ("b", "x = 9 or x = -9"),
                           ("c", "x = 3 only"), ("d", "x = 0")),
             correct_option_id="a",
             answer_rubric="x^2 - 9 = (x - 3)(x + 3).",
             target_concept_id="alg.quadratic_eq",
             prerequisite_tags=["alg.factoring", "alg.special_products"],
             difficulty=Difficulty.HARD, reviewed=True),
    Question(id="q.alg.quadratic_formula.02",
             prompt="Solve using the quadratic formula: x^2 + x - 6 = 0",
             options=_opts(("a", "x = 2 or x = -3"), ("b", "x = -2 or x = 3"),
                           ("c", "x = 6 or x = -1"), ("d", "x = 1 or x = -6")),
             correct_option_id="a",
             answer_rubric="a=1, b=1, c=-6 -> x = (-1 +/- 5)/2 -> 2 or -3.",
             target_concept_id="alg.quadratic_formula",
             prerequisite_tags=["alg.quadratic_eq", "num.roots"],
             difficulty=Difficulty.HARD, reviewed=True),
]
