"""
Concept X-Ray — Hand-authored demo dataset.

Subject: Basic Algebra (grades 6-10).
  30 concepts, 39 prerequisite edges, 20 reviewed quiz questions.
  Deepest chain: num.integers -> ... -> alg.quadratic_formula (9 nodes).
"""
from __future__ import annotations

from .models import (
    Concept, Difficulty, GradeBand, PrerequisiteEdge,
    Question, QuestionOption, RelationshipType,
)

SOURCE = "curriculum-team"
REVIEWER = "r.iyer"


CONCEPTS: list[Concept] = [
    Concept(id="num.integers", title="Integers and the Number Line",
            grade_band=GradeBand.G6_8,
            description="Positive and negative whole numbers and their position on the number line.",
            curriculum_reference="NCERT Class 6, Ch. 6"),
    Concept(id="num.operations", title="Order of Operations (PEMDAS)",
            grade_band=GradeBand.G6_8,
            description="Evaluating numeric expressions using the correct precedence of operations.",
            curriculum_reference="NCERT Class 7, Ch. 1"),
    Concept(id="num.signed", title="Signed Number Arithmetic",
            grade_band=GradeBand.G6_8,
            description="Adding, subtracting, multiplying and dividing signed numbers.",
            curriculum_reference="NCERT Class 7, Ch. 1"),
    Concept(id="num.fractions", title="Fractions and Rational Numbers",
            grade_band=GradeBand.G6_8,
            description="Equivalence, comparison, and arithmetic with fractions.",
            curriculum_reference="NCERT Class 6, Ch. 7"),
    Concept(id="num.decimals", title="Decimals and Percents",
            grade_band=GradeBand.G6_8,
            description="Converting between decimals, fractions, and percents; computing with them.",
            curriculum_reference="NCERT Class 7, Ch. 8"),
    Concept(id="num.exponents", title="Integer Exponents",
            grade_band=GradeBand.G6_8,
            description="Meaning of exponents and the product/quotient rules for integer bases.",
            curriculum_reference="NCERT Class 7, Ch. 13"),
    Concept(id="num.roots", title="Square Roots",
            grade_band=GradeBand.G6_8,
            description="Understanding the square root as the inverse of squaring; perfect and non-perfect squares.",
            curriculum_reference="NCERT Class 8, Ch. 6"),

    Concept(id="alg.variables", title="Variables and Expressions",
            grade_band=GradeBand.G6_8,
            description="Using letters to represent numbers; reading and writing algebraic expressions.",
            curriculum_reference="NCERT Class 6, Ch. 11"),
    Concept(id="alg.substitution", title="Evaluating by Substitution",
            grade_band=GradeBand.G6_8,
            description="Replacing variables with given values and evaluating the expression.",
            curriculum_reference="NCERT Class 7, Ch. 12"),
    Concept(id="alg.combine_like", title="Combining Like Terms",
            grade_band=GradeBand.G6_8,
            description="Identifying like terms and simplifying sums and differences of expressions.",
            curriculum_reference="NCERT Class 7, Ch. 12"),
    Concept(id="alg.distribute", title="Distributive Property",
            grade_band=GradeBand.G6_8,
            description="Expanding a(b + c) = ab + ac and factoring out common factors.",
            curriculum_reference="NCERT Class 7, Ch. 12"),
    Concept(id="alg.one_step", title="One-Step Equations",
            grade_band=GradeBand.G6_8,
            description="Solving equations of the form x + a = b or ax = b.",
            curriculum_reference="NCERT Class 7, Ch. 4"),
    Concept(id="alg.two_step", title="Two-Step Equations",
            grade_band=GradeBand.G6_8,
            description="Solving equations of the form ax + b = c using inverse operations.",
            curriculum_reference="NCERT Class 7, Ch. 4"),
    Concept(id="alg.multi_step", title="Multi-Step Linear Equations",
            grade_band=GradeBand.G9_10,
            description="Solving equations that require distribution and combining like terms first.",
            curriculum_reference="NCERT Class 8, Ch. 2"),
    Concept(id="alg.variables_both_sides", title="Variables on Both Sides",
            grade_band=GradeBand.G9_10,
            description="Solving equations where the variable appears on both sides.",
            curriculum_reference="NCERT Class 8, Ch. 2"),
    Concept(id="alg.inequalities", title="Linear Inequalities",
            grade_band=GradeBand.G9_10,
            description="Solving and graphing one-variable linear inequalities.",
            curriculum_reference="NCERT Class 11, Ch. 6"),

    Concept(id="alg.coordinate", title="The Coordinate Plane",
            grade_band=GradeBand.G6_8,
            description="Plotting and reading ordered pairs (x, y) in four quadrants.",
            curriculum_reference="NCERT Class 9, Ch. 3"),
    Concept(id="alg.slope", title="Slope of a Line",
            grade_band=GradeBand.G9_10,
            description="Computing slope from two points and interpreting it as rate of change.",
            curriculum_reference="NCERT Class 11, Ch. 10"),
    Concept(id="alg.linear_graph", title="Graphing Linear Equations",
            grade_band=GradeBand.G9_10,
            description="Drawing the graph of y = mx + c from a table or slope-intercept form.",
            curriculum_reference="NCERT Class 9, Ch. 4"),
    Concept(id="alg.linear_equation", title="Equation of a Line",
            grade_band=GradeBand.G9_10,
            description="Writing the equation of a line given slope, intercept, or two points.",
            curriculum_reference="NCERT Class 11, Ch. 10"),

    Concept(id="alg.poly_add_sub", title="Adding and Subtracting Polynomials",
            grade_band=GradeBand.G9_10,
            description="Combining polynomial expressions by aligning and combining like terms.",
            curriculum_reference="NCERT Class 9, Ch. 2"),
    Concept(id="alg.poly_mul", title="Multiplying Polynomials",
            grade_band=GradeBand.G9_10,
            description="Using the distributive property repeatedly (FOIL and beyond).",
            curriculum_reference="NCERT Class 9, Ch. 2"),
    Concept(id="alg.gcf", title="Greatest Common Factor",
            grade_band=GradeBand.G6_8,
            description="Finding the GCF of numeric and monomial expressions.",
            curriculum_reference="NCERT Class 6, Ch. 3"),
    Concept(id="alg.factoring", title="Factoring Trinomials",
            grade_band=GradeBand.G9_10,
            description="Factoring quadratics of the form x^2 + bx + c into two binomials.",
            curriculum_reference="NCERT Class 8, Ch. 14"),
    Concept(id="alg.special_products", title="Special Products",
            grade_band=GradeBand.G9_10,
            description="Recognising (a+b)^2, (a-b)^2, and a^2 - b^2 patterns.",
            curriculum_reference="NCERT Class 8, Ch. 14"),

    Concept(id="alg.quadratic_eq", title="Quadratic Equations",
            grade_band=GradeBand.G9_10,
            description="Solving quadratic equations by factoring and by taking square roots.",
            curriculum_reference="NCERT Class 10, Ch. 4"),
    Concept(id="alg.quadratic_formula", title="The Quadratic Formula",
            grade_band=GradeBand.G9_10,
            description="Applying x = (-b +/- sqrt(b^2 - 4ac)) / 2a and interpreting the discriminant.",
            curriculum_reference="NCERT Class 10, Ch. 4"),
    Concept(id="alg.quadratic_graph", title="Graphing Parabolas",
            grade_band=GradeBand.G9_10,
            description="Sketching y = ax^2 + bx + c; vertex, axis of symmetry, and intercepts.",
            curriculum_reference="NCERT Class 10, Ch. 4"),

    Concept(id="alg.systems_sub", title="Systems by Substitution",
            grade_band=GradeBand.G9_10,
            description="Solving a 2x2 linear system by isolating one variable and substituting.",
            curriculum_reference="NCERT Class 10, Ch. 3"),
    Concept(id="alg.systems_elim", title="Systems by Elimination",
            grade_band=GradeBand.G9_10,
            description="Solving a 2x2 linear system by adding/subtracting scaled equations.",
            curriculum_reference="NCERT Class 10, Ch. 3"),
]


def _edge(frm: str, to: str,
          relationship: RelationshipType = RelationshipType.REQUIRES
          ) -> PrerequisiteEdge:
    return PrerequisiteEdge(
        from_concept_id=frm, to_concept_id=to,
        relationship=relationship, source=SOURCE, reviewer=REVIEWER,
    )


EDGES: list[PrerequisiteEdge] = [
    _edge("num.integers", "num.signed"),
    _edge("num.integers", "num.fractions"),
    _edge("num.integers", "num.operations"),
    _edge("num.integers", "num.exponents"),
    _edge("num.integers", "alg.gcf"),
    _edge("num.fractions", "num.decimals"),
    _edge("num.exponents", "num.roots"),

    _edge("num.operations", "alg.variables"),
    _edge("num.signed", "alg.variables"),
    _edge("num.fractions", "alg.variables"),
    _edge("alg.variables", "alg.substitution"),
    _edge("alg.variables", "alg.combine_like"),
    _edge("num.operations", "alg.combine_like"),
    _edge("alg.variables", "alg.gcf"),

    _edge("alg.combine_like", "alg.distribute"),
    _edge("alg.combine_like", "alg.one_step"),
    _edge("alg.combine_like", "alg.poly_add_sub"),
    _edge("alg.distribute", "alg.multi_step"),
    _edge("alg.distribute", "alg.poly_mul"),
    _edge("alg.one_step", "alg.two_step"),
    _edge("alg.two_step", "alg.multi_step"),
    _edge("alg.multi_step", "alg.variables_both_sides"),
    _edge("alg.multi_step", "alg.linear_equation"),
    _edge("alg.variables_both_sides", "alg.inequalities"),
    _edge("alg.variables_both_sides", "alg.systems_sub"),

    _edge("num.signed", "alg.coordinate"),
    _edge("alg.coordinate", "alg.slope"),
    _edge("alg.slope", "alg.linear_graph"),
    _edge("alg.linear_graph", "alg.linear_equation"),

    _edge("alg.gcf", "alg.factoring"),
    _edge("alg.poly_mul", "alg.factoring"),
    _edge("alg.poly_mul", "alg.special_products"),

    _edge("alg.factoring", "alg.quadratic_eq"),
    _edge("alg.special_products", "alg.quadratic_eq"),
    _edge("num.roots", "alg.quadratic_formula"),
    _edge("alg.quadratic_eq", "alg.quadratic_formula"),
    _edge("alg.quadratic_eq", "alg.quadratic_graph"),
    _edge("alg.linear_graph", "alg.quadratic_graph"),

    _edge("alg.systems_sub", "alg.systems_elim"),
]


def _opts(*pairs: tuple[str, str]) -> list[QuestionOption]:
    return [QuestionOption(id=i, text=t) for i, t in pairs]


QUESTIONS: list[Question] = [
    Question(id="q.num.integers.01",
             prompt="Which of the following is the additive inverse of -7?",
             options=_opts(("a", "7"), ("b", "-7"), ("c", "1/7"), ("d", "0")),
             correct_option_id="a",
             answer_rubric="The additive inverse of x sums with x to zero: -7 + 7 = 0.",
             target_concept_id="num.integers", prerequisite_tags=[],
             difficulty=Difficulty.EASY, reviewed=True),
    Question(id="q.num.operations.01",
             prompt="Evaluate: 3 + 4 x 2",
             options=_opts(("a", "14"), ("b", "11"), ("c", "24"), ("d", "9")),
             correct_option_id="b",
             answer_rubric="Multiplication before addition: 4 x 2 = 8, then 3 + 8 = 11.",
             target_concept_id="num.operations",
             prerequisite_tags=["num.integers"],
             difficulty=Difficulty.EASY, reviewed=True),
    Question(id="q.num.signed.01",
             prompt="Compute: -5 + 3",
             options=_opts(("a", "-8"), ("b", "-2"), ("c", "2"), ("d", "8")),
             correct_option_id="b",
             answer_rubric="Start at -5 and move 3 units right on the number line: -2.",
             target_concept_id="num.signed",
             prerequisite_tags=["num.integers"],
             difficulty=Difficulty.EASY, reviewed=True),
    Question(id="q.num.fractions.01",
             prompt="Compute: 1/2 + 1/3",
             options=_opts(("a", "2/5"), ("b", "5/6"), ("c", "1/6"), ("d", "3/5")),
             correct_option_id="b",
             answer_rubric="Common denominator 6: 3/6 + 2/6 = 5/6.",
             target_concept_id="num.fractions",
             prerequisite_tags=["num.integers"],
             difficulty=Difficulty.MEDIUM, reviewed=True),
    Question(id="q.num.exponents.01",
             prompt="Evaluate: 2^3 x 2^2",
             options=_opts(("a", "32"), ("b", "64"), ("c", "16"), ("d", "12")),
             correct_option_id="a",
             answer_rubric="Same base, add exponents: 2^(3+2) = 2^5 = 32.",
             target_concept_id="num.exponents",
             prerequisite_tags=["num.integers"],
             difficulty=Difficulty.MEDIUM, reviewed=True),
    Question(id="q.num.roots.01",
             prompt="Evaluate: sqrt(81)",
             options=_opts(("a", "9"), ("b", "8"), ("c", "40.5"), ("d", "18")),
             correct_option_id="a",
             answer_rubric="9 x 9 = 81, so sqrt(81) = 9.",
             target_concept_id="num.roots",
             prerequisite_tags=["num.exponents"],
             difficulty=Difficulty.EASY, reviewed=True),
    Question(id="q.alg.variables.01",
             prompt="If x = 4, what is the value of 3x + 2?",
             options=_opts(("a", "10"), ("b", "12"), ("c", "14"), ("d", "18")),
             correct_option_id="c",
             answer_rubric="Substitute x: 3(4) + 2 = 12 + 2 = 14.",
             target_concept_id="alg.variables",
             prerequisite_tags=["num.operations", "num.signed"],
             difficulty=Difficulty.EASY, reviewed=True),
    Question(id="q.alg.combine_like.01",
             prompt="Simplify: 5x + 3y - 2x + y",
             options=_opts(("a", "3x + 4y"), ("b", "7x + 2y"),
                           ("c", "3x + 2y"), ("d", "8xy")),
             correct_option_id="a",
             answer_rubric="x-terms: 5x - 2x = 3x. y-terms: 3y + y = 4y.",
             target_concept_id="alg.combine_like",
             prerequisite_tags=["alg.variables", "num.operations"],
             difficulty=Difficulty.MEDIUM, reviewed=True),
    Question(id="q.alg.distribute.01",
             prompt="Expand: 3(x + 4)",
             options=_opts(("a", "3x + 4"), ("b", "3x + 12"),
                           ("c", "x + 12"), ("d", "3x - 12")),
             correct_option_id="b",
             answer_rubric="3*x + 3*4 = 3x + 12.",
             target_concept_id="alg.distribute",
             prerequisite_tags=["alg.combine_like"],
             difficulty=Difficulty.EASY, reviewed=True),
    Question(id="q.alg.one_step.01",
             prompt="Solve for x: x + 7 = 12",
             options=_opts(("a", "x = 5"), ("b", "x = 19"),
                           ("c", "x = -5"), ("d", "x = 7")),
             correct_option_id="a",
             answer_rubric="Subtract 7 from both sides: x = 5.",
             target_concept_id="alg.one_step",
             prerequisite_tags=["alg.combine_like"],
             difficulty=Difficulty.EASY, reviewed=True),
    Question(id="q.alg.two_step.01",
             prompt="Solve for x: 2x + 3 = 11",
             options=_opts(("a", "x = 4"), ("b", "x = 7"),
                           ("c", "x = 5.5"), ("d", "x = 8")),
             correct_option_id="a",
             answer_rubric="Subtract 3: 2x = 8. Divide by 2: x = 4.",
             target_concept_id="alg.two_step",
             prerequisite_tags=["alg.one_step"],
             difficulty=Difficulty.MEDIUM, reviewed=True),
    Question(id="q.alg.multi_step.01",
             prompt="Solve for x: 3(x - 2) = 9",
             options=_opts(("a", "x = 5"), ("b", "x = 3"),
                           ("c", "x = 1"), ("d", "x = 11")),
             correct_option_id="a",
             answer_rubric="Divide by 3: x - 2 = 3. Add 2: x = 5.",
             target_concept_id="alg.multi_step",
             prerequisite_tags=["alg.distribute", "alg.two_step"],
             difficulty=Difficulty.MEDIUM, reviewed=True),
    Question(id="q.alg.variables_both_sides.01",
             prompt="Solve for x: 4x - 3 = 2x + 7",
             options=_opts(("a", "x = 5"), ("b", "x = 2"),
                           ("c", "x = -5"), ("d", "x = 10")),
             correct_option_id="a",
             answer_rubric="Subtract 2x: 2x - 3 = 7. Add 3: 2x = 10. Divide by 2: x = 5.",
             target_concept_id="alg.variables_both_sides",
             prerequisite_tags=["alg.multi_step"],
             difficulty=Difficulty.MEDIUM, reviewed=True),
    Question(id="q.alg.slope.01",
             prompt="Find the slope of the line through (1, 2) and (3, 8).",
             options=_opts(("a", "3"), ("b", "1/3"), ("c", "5"), ("d", "-3")),
             correct_option_id="a",
             answer_rubric="m = (8 - 2) / (3 - 1) = 6/2 = 3.",
             target_concept_id="alg.slope",
             prerequisite_tags=["alg.coordinate"],
             difficulty=Difficulty.MEDIUM, reviewed=True),
    Question(id="q.alg.linear_equation.01",
             prompt="Write the equation of the line with slope 2 passing through (0, -1).",
             options=_opts(("a", "y = 2x - 1"), ("b", "y = -2x + 1"),
                           ("c", "y = 2x + 1"), ("d", "y = x - 2")),
             correct_option_id="a",
             answer_rubric="Slope-intercept y = mx + c with m = 2, c = -1.",
             target_concept_id="alg.linear_equation",
             prerequisite_tags=["alg.linear_graph", "alg.multi_step"],
             difficulty=Difficulty.MEDIUM, reviewed=True),
    Question(id="q.alg.gcf.01",
             prompt="What is the GCF of 12x^2 and 18x?",
             options=_opts(("a", "6x"), ("b", "6x^2"), ("c", "3x"), ("d", "12x")),
             correct_option_id="a",
             answer_rubric="GCF(12, 18) = 6, common variable power is x, so GCF = 6x.",
             target_concept_id="alg.gcf",
             prerequisite_tags=["num.integers", "alg.variables"],
             difficulty=Difficulty.MEDIUM, reviewed=True),
    Question(id="q.alg.poly_mul.01",
             prompt="Expand: (x + 3)(x + 4)",
             options=_opts(("a", "x^2 + 7x + 12"), ("b", "x^2 + 12x + 7"),
                           ("c", "x^2 + 7x + 7"), ("d", "x^2 + 12")),
             correct_option_id="a",
             answer_rubric="FOIL: x*x + 4x + 3x + 12 = x^2 + 7x + 12.",
             target_concept_id="alg.poly_mul",
             prerequisite_tags=["alg.distribute", "alg.combine_like"],
             difficulty=Difficulty.MEDIUM, reviewed=True),
    Question(id="q.alg.factoring.01",
             prompt="Factor: x^2 + 5x + 6",
             options=_opts(("a", "(x + 2)(x + 3)"), ("b", "(x + 1)(x + 6)"),
                           ("c", "(x - 2)(x - 3)"), ("d", "(x + 6)(x - 1)")),
             correct_option_id="a",
             answer_rubric="Need two numbers multiplying to 6 and adding to 5: 2 and 3.",
             target_concept_id="alg.factoring",
             prerequisite_tags=["alg.gcf", "alg.poly_mul"],
             difficulty=Difficulty.HARD, reviewed=True),
    Question(id="q.alg.quadratic_eq.01",
             prompt="Solve by factoring: x^2 - 4 = 0",
             options=_opts(("a", "x = 2 or x = -2"), ("b", "x = 4 or x = -4"),
                           ("c", "x = 2 only"), ("d", "x = 0")),
             correct_option_id="a",
             answer_rubric="x^2 - 4 = (x - 2)(x + 2), so x = 2 or x = -2.",
             target_concept_id="alg.quadratic_eq",
             prerequisite_tags=["alg.factoring", "alg.special_products"],
             difficulty=Difficulty.HARD, reviewed=True),
    Question(id="q.alg.quadratic_formula.01",
             prompt="Use the quadratic formula to solve x^2 - 2x - 3 = 0.",
             options=_opts(("a", "x = 3 or x = -1"), ("b", "x = -3 or x = 1"),
                           ("c", "x = 3 or x = 1"), ("d", "x = -3 or x = -1")),
             correct_option_id="a",
             answer_rubric="a=1, b=-2, c=-3 -> x = (2 +/- 4)/2 -> x = 3 or x = -1.",
             target_concept_id="alg.quadratic_formula",
             prerequisite_tags=["alg.quadratic_eq", "num.roots"],
             difficulty=Difficulty.HARD, reviewed=True),
    Question(id="q.alg.systems_sub.01",
             prompt="Solve the system: y = x + 1 and x + y = 5",
             options=_opts(("a", "(2, 3)"), ("b", "(3, 2)"),
                           ("c", "(1, 2)"), ("d", "(5, 4)")),
             correct_option_id="a",
             answer_rubric="Substitute: x + (x + 1) = 5 -> 2x = 4 -> x = 2, y = 3.",
             target_concept_id="alg.systems_sub",
             prerequisite_tags=["alg.variables_both_sides"],
             difficulty=Difficulty.HARD, reviewed=True),
]
